README.md

testing new branch verification

Add image immutable

---

README.md

add Book
add "Learn Kubernetes Security: Securely orchestrate, scale, and manage your microservices in Kubernetes deployments"

add K8s security book

---

README.md

- add intro/basic containers & k8s security tutorial
- add CKS activity guide
- add CKS killer.sh practice exam

add tutorial and more coverage

---

README.md

- add code in action videos for LKS book
- add killer.sh discount code

add code in action videos for LKS book

---

license.txt

- Add creative commons Attribution-ShareAlike 4.0 International

Add license.txt

---

README.md

Add stargazers chart

---

README.md

- Update supply-chain security
- Update containers runtimeClass URL

Feat sandbox

---

README.md

- Add Ingress security
- API endpoint security
- Verify Image/bianry digest

Add more k8s.io relavent content

---

README.md

Add todo emoji

---

README.md

- add easter ctf repo
- add stackrox GH repo

add ctf and studyguide

---

README.md

update Exam is GA

---

README.md

fix a typo in READMe.md

---

README.md

- add Kim's Udemy course
- reorganize some links

add CKS 2020 udemy course

---

README.md

- add LinuxFoundation new k8s security course
- housekeeping and clean up

add LinuxFoundation new k8s security course

---

README.md

- add exam duration, passing score

Add general exam info

---

README.md

- update exam info
- update date of LFS 260

update exam info

---

README.md

Hi @walidshaari ! Thanks for putting this together.
This is very useful!
This patch adds some more resources for Falco and does change to follow the [brand guidelines](https://github.com/falcosecurity/falco/tree/master/brand) for naming .
Thanks again,
Lore
Signed-off-by: Lorenzo Fontana <lo@linux.com>

Update Falco links and details

---

README.md

add CKS course blackfriday discount

add CKS course blackfriday discount

---

README.md
generic-kubernetes-containers-security/Kubernetes.md

I just add new directory that we discussed on this [issue](https://github.com/walidshaari/Certified-Kubernetes-Security-Specialist/issues/26).

Categorize resources to relevant topics

---

generic-kubernetes-containers-security/Kubernetes.md

- add CNCF sig-sec white paper

add CNCF sig-sec white paper

---

README.md

add extra allowed URLs

---

README.md

- add kube-bench tool url
-  minor formatting cleanups

add kube-bench

---

README.md

- cleanup and reformating
- cloud metadata network policy
- elobrate on cluster api access
- add CKS challenges:

End of year updates

---

README.md

- emphasize exam kubernetes version
- add Zeal Vora CKS course with discount

minor year end updates

---

README.md

- add back udemy CKS course with discount
- fix issue #43

fix issue #43

---

generic-kubernetes-containers-security/README.md

- Changed titles
- Add Kubernetes security book

update generic resources

---

README.md

add twitch channel

---

README.md

update exam version

---

README.md

Adding CKS book

---

README.md

- Add Saiyam's Pathak OpenSource Discord cks channel
- Add Mumshad CKS new course in KodeCloud.

Add new CKS course and discord channel

---

README.md

- add admission controller imagePolicyWebHook URL

add ImagePolicyWebhook

---

README.md

Please check & approve the PR.
Thanks !!

add free CKS Exam simulator details from Linux Foundation

---

README.md

updated Falco kubernetes install

fix for issue #56

---

README.md

update readme CKS is now using 1.22

CKS is now using 1.22

---

README.md

Add Falco 101 course

---

hands-on/00-kind-cluster/kind-1m3w-nocni.yaml

updated naming of the worker nodes on the kind cluster yaml

updated kind cluster yaml

---

README.md

Remove PodSecurityPolicy deprecated and change with Pod Security Admission

Remove PodSecurityPolicy deprecated

---

README.md

feat(youtube-videos): add CKS Webinar 2022
